### ISSUE TITLE
Error downloading data

### ISSUE THREAD

**Issue by miriasmata** [GeoscienceAustralia/ptha#43] opened 2024-05-01 12:58 UTC
Hello,
I am trying to use the rptha but I am having some issues accessing the data.

I am trying to run this example code:  https://github.com/GeoscienceAustralia/ptha/blob/master/ptha_access/example_event_access_scripts/random_scenarios_non_uniform_and_importance_sampling/random_scenario_sampling.md

When I try to run the line that access the data:  <<source_zone_scenarios = ptha18$get_source_zone_events_data(source_zone,  slip_type='stochastic')>> I get the following error:

Note:Caching=1
Error:curl error: Timeout was reached
curl error details: 
Warning:oc_open: Could not read url
Error in R_nc4_open: NetCDF: I/O failure
Error in nc_open(filename) : 
  Error in nc_open trying to open file [stringlength=4096]https://dapds00.nci.org.au/thredds/dodsC/fj6/PTHA/AustPTHA_1/SOURCE_ZONES/kermadectonga2/TSUNAMI_EVENTS/all_stochastic_slip_earthquake_events_kermadectonga2.nc (return_on_error= FALSE )

Could you help me with this issue? What is causing the error?

Thanks in advance,
Marisol Irías Mata

**Comment by gareth-d-ga** [comment] 2024-05-02 13:21
Hi. 
The NCI servers were closed for maintenance on May 1-2. It should be back up again now. 
Let me know if you still have trouble.

**Comment by miriasmata** [comment] 2024-05-08 07:35
Hi Gareth,

Thank you for your response. Now, I am able to get some information but not all of it. When I try to download the shape files or tiff files I receive an error. The files are downloaded into my machine but I cannot open them.

For instance, I get this error running the source(hazard_point_plot.R):

Error: Cannot open "D:\Rcode\Repositories\ptha\ptha_access\SOURCE_ZONES\alaskaaleutians\EQ_SOURCE\unit_source_grid\alaskaaleutians.shp"; The source could be corrupt or not supported. See `st_drivers()` for a list of supported formats.
In addition: Warning message:
In CPL_read_ogr(dsn, layer, query, as.character(options), quiet,  :
  GDAL Error 4: Record count in .shx header is -11, which seems
unreasonable.  Assuming header is corrupt.

Thanks in advance,
Marisol Irías Mata

**Comment by gareth-nx** [comment] 2024-05-15 07:54
Could you please check whether this file exists, and if yes, whether it is readable?
``` 
"D:\Rcode\Repositories\ptha\ptha_access\SOURCE_ZONES\alaskaaleutians\EQ_SOURCE\unit_source_grid\alaskaaleutians.shp"
```

It sounds like the code has downloaded data to your machine (which it should) but is then having trouble reading it (which it shouldn't).

If you think the file might be corrupted, consider deleting the `SOURCE_ZONES` folder (which isn't version controlled) and trying again.

**Comment by miriasmata** [comment] 2024-06-04 15:03
Hi Gareth,

Thank you again for the response. I am still having the same issue. I followed your advice and deleted the folder with the shapefiles but the error persisted. Moreover, I was trying to get the initial conditions geotiff files by running the following line:

# Get the initial condition as a geo-referenced raster
initial_condition = get_initial_condition_for_event(puysegur, row_index)

However, I am also getting an error. The error is:

Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file.

I am not sure if the problems are related but could you help me with this issue? 

Thanks,
Marisol

**Comment by gareth-d-ga** [comment] 2024-06-04 23:40
Hi Marisol,

**See further progress on this a few posts down**.

The source of these errors isn't obvious. Below I tried running a few things to see if there were problems on my end -- but I cannot reproduce the problems that you're getting.

Some things to consider:
* Is your internet connection unstable?
  * This would be the simplest explanation.
* Are you using a relatively up-to-date version of the code? 
  * Say from the last few months? That said, I wouldn't have thought this would matter. 
  * Unrelated: At the end of this month the NCI THREDDS server will move to a new location, and you'll need to be using a recent version of the code (since May 29 2024), see comment [here](https://github.com/GeoscienceAustralia/ptha/blob/master/ptha_access/README.md) right after the title.
* Are you using a relatively up-to-date version of R and packages?
  *  Not sure if this will matter, but the R spatial ecosystem has changed quite a bit in the last few years.
* Can you successfully run the test script, as described early in the [DETAILED README](https://github.com/GeoscienceAustralia/ptha/blob/master/ptha_access/DETAILED_README.Rmd)?
* It looks like you're running windows? We don't test the code regularly on windows, although I hear of other people having success. I wonder if it would be any different if you ran the code via a linux machine (e.g. using virtualbox or similar)?

## Check of the random scenario sampling code.

Just now I successfully ran the code in https://github.com/GeoscienceAustralia/ptha/blob/master/ptha_access/example_event_access_scripts/random_scenarios_non_uniform_and_importance_sampling/random_scenario_sampling.Rmd
which triggered your initial comment.
```
> library(knitr)
> library(rptha)
Loading required package: geosphere
Loading required package: sp
Loading required package: sf
Linking to GEOS 3.10.2, GDAL 3.4.1, PROJ 8.2.1; sf_use_s2() is TRUE
Loading required package: raster
Loading required package: FNN
Loading required package: minpack.lm
Loading required package: geometry
Loading required package: ncdf4
>  knit('random_scenario_sampling.Rmd')


processing file: random_scenario_sampling.Rmd
                                                                                                                             
output file: random_scenario_sampling.md

[1] "random_scenario_sampling.md"

```
I know it worked because the file `random_scenario_sampling.md` was recreated without any changes. 

## `hazard_point_plot.R`

Firstly note this isn't a particularly useful code - it's ages since I tried to run it. It's probably better to just use GIS for visualisation.

Anyway, I tried to run it with `source('hazard_points_plot.R', echo=TRUE, max.deparse.length=Inf)`. Here the extra arguments just print out the progress, but shouldn't change the result.

This failed for me with an error like this when trying to create the map
```
> local_map = plot_interactive_map()
Error in copyDependencyToDir(dep, libdir, FALSE) : 
  Can't copy dependency files that don't exist: '/tmp/RtmpQlErYW/leaflet-providers_1.9.0.js'
```

The problem was that by default, the code tries to read an old cache of the map data structure, rather than regenerating it. The cache file is `"DATA/interactive_map.RDS"`

The solution was to set `REFRESH_MAP=TRUE` to force the code to re-generate the file. Then I got the map in my web browser. It looks like this is always needed now (so I will change the code). I suspect that the mapping packages have updated their data structures since I last ran that code.

Unfortunately this doesn't sound like the same issue you mentioned.

## Initial condition code

That's contained [here](https://github.com/GeoscienceAustralia/ptha/blob/master/ptha_access/DETAILED_README.Rmd) and to check it I did:
```
> library(knitr)
> knit('DETAILED_README.Rmd')
```
This worked correctly (regenerating `DETAILED_README.md` without any changes).

**Comment by gareth-d-ga** [comment] 2024-06-04 23:44
The cache issue with `hazard_points_plot.R` should be addressed by [this change](https://github.com/GeoscienceAustralia/ptha/commit/81b5a204a057ca1fb5da39b24c000311ae7460ba). Although I don't think this is addressing your problem.

**Comment by gareth-d-ga** [comment] 2024-06-05 00:36
Just now I tried to run some of the codes from my windows machine, and can reproduce the error with
```
> library(knitr)
> knit('DETAILED_README.Rmd')
```
which fails with the error you mention
```
Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer", :
Cannot create a RasterLayer object from this file.
```

The same code works on my linux machine, even after removing old cached data.

So it's something to do with the automated raster download causing problems on Windows, which I'll look into.

**Comment by gareth-d-ga** [comment] 2024-06-05 01:05
On my windows machine, automated binary file downloads using the R function `download.file` appear to be corrupting the file. This seems to relate to the following comment in [the help page](https://www.rdocumentation.org/packages/utils/versions/3.6.2/topics/download.file) for `download.file`
```
     The choice of binary transfer (‘mode = "wb"’ or ‘"ab"’) is
     important on Windows, since unlike Unix-alikes it does distinguish
     between text and binary files and for text transfers changes ‘\n’
     line endings to ‘\r\n’ (aka ‘CRLF’).

```

I made some updates this morning that should fix this issue. With that you should be able to work with downloaded rasters (create initial conditions etc). 

Can you please check if it works?

There is another issue (apparently unrelated) with creating a shapefile in `hazard_points_plot.R` which should need a different fix.

**Comment by gareth-d-ga** [comment] 2024-06-05 02:14
The error in `hazard_points_plot.R` was caused by the code trying to write a shapefile with attribute names greater than 10 characters long. Actually this seems to affect linux as well as windows, not sure why I didn't see it above.

The code previously worked but is technically illegal for a shapefile. I suspect that the R spatial ecosystem updates since 2023-present caused this 10 character limit to be enforced, rather than writing "technically invalid" shapefiles.

The solution is to not write the shapefile - the code still works in any case, and the data is available as a csv. With this change it is now working for me on windows and linux.

**Can you please try to completely update your R code, reinstall (including rptha and dependencies) with a recent version of R, and let me know if it works now?**

**Comment by miriasmata** [comment] 2024-06-05 12:06
Thank you for your fast reply and for updating the code. Now it runs smoothly. I was able to download the initial conditions and visualize the results both in R and QGIS.

**Comment by gareth-d-ga** [comment] 2024-06-05 22:58
Great, thanks for reporting.

**Closed as completed by gareth-d-ga** 2024-06-05 22:58 UTC
